OPS-12 - PostSync check secrets are there

diff --git a/argocd/manifests/job-post-sync-evidence.yaml b/argocd/manifests/job-post-sync-evidence.yaml
--- a/argocd/manifests/job-post-sync-evidence.yaml
+++ b/argocd/manifests/job-post-sync-evidence.yaml
@@ -32,6 +32,23 @@ spec:
             EVD_DEMO_APP_NAME=quotopia-app
             EVD_DEMO_APP_VER=30
 
+            echo "JF secrets:"
+            ls -l /etc/jfsecrets
+
+            echo "Signing key secrets:
+            ls -l /etc/signkey
+
+            # Check the required secrets exist.
+            if [ ! -f /etc/jfsecrets/JF_TOKEN ]; then
+                echo "Secret /etc/jfsecrets/JF_TOKEN is missing."
+                exit 1
+            fi
+
+            if [ ! -f /etc/signkey/SIGNING_KEY ]; then
+                echo "Secret /etc/signkey/SIGNING_KEY is missing."
+                exit 1
+            fi
+
             # Install jq
             echo "Installing jq"
             apt-get update -y 1>/dev/null 2>/dev/null
