print sonar task ID

diff --git a/.github/workflows/quoteofday-ci.yml b/.github/workflows/quoteofday-ci.yml
--- a/.github/workflows/quoteofday-ci.yml
+++ b/.github/workflows/quoteofday-ci.yml
@@ -85,8 +85,11 @@ jobs:
         cd quoteofday
         echo "Searching for report-task.txt file..."
         REPORT_TASK_FILE=$(find . -name 'report-task.txt' | head -n1)
-        [ -f "$REPORT_TASK_FILE" ] || echo "repot.task.txt file was not found."
-        [ -f "$REPORT_TASK_FILE" ] && cat "$REPORT_TASK_FILE"
+        [ -f "$REPORT_TASK_FILE" ] || echo "repot-task.txt file was not found."
+        [ -f "$REPORT_TASK_FILE" ] && echo "report-tesk.txt content:" && cat "$REPORT_TASK_FILE"
+        [ -f "$REPORT_TASK_FILE" ] && SONAR_TASK_ID=$(grep 'ceTaskId=' "$REPORT_TASK_FILE" | cut -d'=' -f2)
+        [ "" == "$SONAR_TASK_ID" ] && echo "Sonar task ID was not found."
+        [ "" != "$SONAR_TASK_ID" ] && echo "Sonar task ID: $SONAR_TASK_ID"
 
     - name: Create Test Evidence JSON
       run: |
